-- Stage 3-6: catalog, goal tasks, allowance. Methods stay plugins.

INSERT INTO public.education_methods (id, name, tagline, description, sort_order)
VALUES
  ('tracks', 'מסלולי אקשן', 'מסלול משימות לכל מתנה', 'רק משימות אקשן מקדמות את המתנה. משימות בית נותנות נקודות ניסיון.', 1),
  ('classic', 'כל משימה נחשבת', 'כל משימה מקרבת למטרה', 'בית ואקשן באותו מסלול. כל משימה מקדמת את המתנה.', 2),
  ('pocket_money', 'דמי כיס', 'חיסכון אמיתי בשקלים', 'סכום בסיס ומשימות מזכות שקלים. בלי יתרה שלילית.', 3)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, description = EXCLUDED.description;

ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS goal_id UUID REFERENCES public.goals(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS repeat_target INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS repeat_done INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS advances_goal BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.content_categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS public.reward_tasks (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  kind public.task_kind NOT NULL
);
CREATE TABLE IF NOT EXISTS public.reward_price_ranges (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  min_ils NUMERIC(10,2) NOT NULL,
  max_ils NUMERIC(10,2),
  task_count INT NOT NULL,
  sort_order INT NOT NULL
);
CREATE TABLE IF NOT EXISTS public.reward_paths (
  id TEXT PRIMARY KEY,
  range_id TEXT NOT NULL REFERENCES public.reward_price_ranges(id) ON DELETE CASCADE,
  path_index INT NOT NULL,
  name TEXT NOT NULL,
  UNIQUE (range_id, path_index)
);
CREATE TABLE IF NOT EXISTS public.reward_path_tasks (
  path_id TEXT NOT NULL REFERENCES public.reward_paths(id) ON DELETE CASCADE,
  task_id TEXT NOT NULL REFERENCES public.reward_tasks(id) ON DELETE CASCADE,
  sort_order INT NOT NULL,
  PRIMARY KEY (path_id, task_id)
);
CREATE TABLE IF NOT EXISTS public.child_allowances (
  child_id UUID PRIMARY KEY REFERENCES public.child_profiles(id) ON DELETE CASCADE,
  period TEXT NOT NULL DEFAULT 'weekly',
  base_amount NUMERIC(10,2) NOT NULL DEFAULT 20,
  payout_day INT NOT NULL DEFAULT 1,
  home_amount NUMERIC(10,2) NOT NULL DEFAULT 2,
  action_amount NUMERIC(10,2) NOT NULL DEFAULT 5,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT ON public.content_categories, public.reward_tasks, public.reward_price_ranges, public.reward_paths, public.reward_path_tasks TO anon, authenticated;
GRANT ALL ON public.content_categories, public.reward_tasks, public.reward_price_ranges, public.reward_paths, public.reward_path_tasks, public.child_allowances TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.child_allowances TO authenticated;
ALTER TABLE public.content_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reward_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reward_price_ranges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reward_paths ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reward_path_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.child_allowances ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS cat_read ON public.content_categories;
DROP POLICY IF EXISTS rt_read ON public.reward_tasks;
DROP POLICY IF EXISTS rr_read ON public.reward_price_ranges;
DROP POLICY IF EXISTS rp_read ON public.reward_paths;
DROP POLICY IF EXISTS rpt_read ON public.reward_path_tasks;
DROP POLICY IF EXISTS allow_read ON public.child_allowances;
DROP POLICY IF EXISTS allow_write ON public.child_allowances;
CREATE POLICY cat_read ON public.content_categories FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY rt_read ON public.reward_tasks FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY rr_read ON public.reward_price_ranges FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY rp_read ON public.reward_paths FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY rpt_read ON public.reward_path_tasks FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY allow_read ON public.child_allowances FOR SELECT TO authenticated
  USING (public.can_access_child(auth.uid(), child_id));
CREATE POLICY allow_write ON public.child_allowances FOR ALL TO authenticated
  USING (public.can_manage_child(auth.uid(), child_id))
  WITH CHECK (public.can_manage_child(auth.uid(), child_id));

INSERT INTO public.reward_price_ranges (id, label, min_ils, max_ils, task_count, sort_order) VALUES ('r1', $mj$עד 300 ש״ח$mj$, 0, 300, 4, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r1p1', 'r1', 1, $mj$צמיחה ויוזמה$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r1p1', 't_b3269810e4', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r1p1', 't_a157213497', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r1p1', 't_c182c55caa', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r1p1', 't_08b7179c0f', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r1p2', 'r1', 2, $mj$נתינה ומנהיגות$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r1p2', 't_c0e0a9e8c3', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r1p2', 't_492ec611fe', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r1p2', 't_6d6941bf5f', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r1p2', 't_6d8ad3dac6', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r1p3', 'r1', 3, $mj$בית וקשרים$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r1p3', 't_23379dee7c', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r1p3', 't_3149473f1c', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r1p3', 't_a2ed1c9aa1', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r1p3', 't_a1e49c3bad', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_price_ranges (id, label, min_ils, max_ils, task_count, sort_order) VALUES ('r2', $mj$300–600 ש״ח$mj$, 300, 600, 6, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r2p1', 'r2', 1, $mj$צמיחה ויוזמה$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p1', 't_6912dce8ed', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p1', 't_5d328d9a9f', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p1', 't_a1e49c3bad', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p1', 't_0d0d0f636c', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p1', 't_8f9f1777d7', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p1', 't_4f6f3eb9dd', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r2p2', 'r2', 2, $mj$נתינה ומנהיגות$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p2', 't_c182c55caa', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p2', 't_3ebb1e4ab2', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p2', 't_e62df589f9', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p2', 't_85a6fa4a01', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p2', 't_00ffb0476f', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p2', 't_bf1806c81b', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r2p3', 'r2', 3, $mj$בית וקשרים$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p3', 't_e9b8f2626d', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p3', 't_d073688e9c', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p3', 't_d698d1bb61', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p3', 't_46ac5eb1c9', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p3', 't_b3a451b600', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r2p3', 't_47b9a10e48', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_price_ranges (id, label, min_ils, max_ils, task_count, sort_order) VALUES ('r3', $mj$600–1,000 ש״ח$mj$, 600, 1000, 8, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r3p1', 'r3', 1, $mj$צמיחה ויוזמה$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p1', 't_a35c1f4f17', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p1', 't_b78add04ac', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p1', 't_46ac5eb1c9', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p1', 't_6deca4cb5c', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p1', 't_498ca4be6f', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p1', 't_b3a451b600', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p1', 't_735fd7aee1', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p1', 't_8229128602', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r3p2', 'r3', 2, $mj$נתינה ומנהיגות$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p2', 't_a1e49c3bad', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p2', 't_4f6f3eb9dd', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p2', 't_3149473f1c', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p2', 't_9eb93eac2c', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p2', 't_a2ed1c9aa1', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p2', 't_23379dee7c', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p2', 't_8d1d405dd9', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p2', 't_46ac5eb1c9', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r3p3', 'r3', 3, $mj$בית וקשרים$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p3', 't_e98e0b31a9', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p3', 't_d0362bae5c', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p3', 't_8646c211a3', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p3', 't_36944a11eb', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p3', 't_ead695b703', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p3', 't_af79802265', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p3', 't_caa46b58fd', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r3p3', 't_a157213497', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_price_ranges (id, label, min_ils, max_ils, task_count, sort_order) VALUES ('r4', $mj$1,000–1,500 ש״ח$mj$, 1000, 1500, 15, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r4p1', 'r4', 1, $mj$צמיחה ויוזמה$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_8229128602', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_28dcfa847e', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_36944a11eb', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_4cde197d65', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_9f195262d3', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_ead695b703', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_757999bfee', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_6d8ad3dac6', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_c8fd439a8a', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_c0e0a9e8c3', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_bc857d3dbb', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_6d6941bf5f', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_492ec611fe', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_6c5ff14824', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p1', 't_00ffb0476f', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r4p2', 'r4', 2, $mj$נתינה ומנהיגות$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_46ac5eb1c9', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_b3a451b600', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_d073688e9c', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_47b9a10e48', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_d698d1bb61', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_e9b8f2626d', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_c07c096103', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_36944a11eb', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_ead695b703', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_d0362bae5c', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_af79802265', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_8646c211a3', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_e98e0b31a9', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_caa46b58fd', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p2', 't_c0e0a9e8c3', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r4p3', 'r4', 3, $mj$בית וקשרים$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_a157213497', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_8f9f1777d7', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_b3269810e4', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_c0e0a9e8c3', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_492ec611fe', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_915ee91832', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_ee828534ba', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_5d328d9a9f', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_498ca4be6f', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_6912dce8ed', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_c182c55caa', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_3ebb1e4ab2', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_735fd7aee1', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_739ca33861', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r4p3', 't_b78add04ac', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_price_ranges (id, label, min_ils, max_ils, task_count, sort_order) VALUES ('r5', $mj$1,500–2,500 ש״ח$mj$, 1500, 2500, 20, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r5p1', 'r5', 1, $mj$צמיחה ויוזמה$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_6d8ad3dac6', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_c8fd439a8a', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_c0e0a9e8c3', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_bc857d3dbb', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_6d6941bf5f', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_492ec611fe', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_6c5ff14824', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_00ffb0476f', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_ca281ca1ad', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_c182c55caa', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_bf1806c81b', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_e62df589f9', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_3ebb1e4ab2', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_85a6fa4a01', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_a2ed1c9aa1', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_23379dee7c', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_a1e49c3bad', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_8d1d405dd9', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_3149473f1c', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p1', 't_4f6f3eb9dd', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r5p2', 'r5', 2, $mj$נתינה ומנהיגות$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_36944a11eb', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_ead695b703', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_d0362bae5c', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_af79802265', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_8646c211a3', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_e98e0b31a9', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_caa46b58fd', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_c0e0a9e8c3', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_492ec611fe', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_8f9f1777d7', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_915ee91832', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_b3269810e4', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_a157213497', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_ee828534ba', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_c182c55caa', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_3ebb1e4ab2', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_498ca4be6f', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_735fd7aee1', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_6912dce8ed', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p2', 't_5d328d9a9f', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r5p3', 'r5', 3, $mj$בית וקשרים$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_5d328d9a9f', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_498ca4be6f', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_6912dce8ed', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_c182c55caa', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_3ebb1e4ab2', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_735fd7aee1', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_739ca33861', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_b78add04ac', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_9f195262d3', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_a35c1f4f17', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_a1e49c3bad', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_4f6f3eb9dd', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_757999bfee', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_08b7179c0f', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_28dcfa847e', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_6d6941bf5f', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_8229128602', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_46ac5eb1c9', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_b3a451b600', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r5p3', 't_6c5ff14824', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_price_ranges (id, label, min_ils, max_ils, task_count, sort_order) VALUES ('r6', $mj$2,500–5,000 ש״ח$mj$, 2500, 5000, 24, 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r6p1', 'r6', 1, $mj$צמיחה ויוזמה$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_00ffb0476f', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_ca281ca1ad', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_c182c55caa', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_bf1806c81b', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_e62df589f9', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_3ebb1e4ab2', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_85a6fa4a01', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_a2ed1c9aa1', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_23379dee7c', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_a1e49c3bad', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_8d1d405dd9', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_3149473f1c', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_4f6f3eb9dd', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_9eb93eac2c', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_d698d1bb61', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_e9b8f2626d', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_46ac5eb1c9', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_c07c096103', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_d073688e9c', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_b3a451b600', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_47b9a10e48', 21) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_8646c211a3', 22) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_e98e0b31a9', 23) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p1', 't_36944a11eb', 24) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r6p2', 'r6', 2, $mj$נתינה ומנהיגות$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_c0e0a9e8c3', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_492ec611fe', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_8f9f1777d7', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_915ee91832', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_b3269810e4', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_a157213497', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_ee828534ba', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_c182c55caa', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_3ebb1e4ab2', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_498ca4be6f', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_735fd7aee1', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_6912dce8ed', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_5d328d9a9f', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_739ca33861', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_a1e49c3bad', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_4f6f3eb9dd', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_9f195262d3', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_757999bfee', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_a35c1f4f17', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_b78add04ac', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_08b7179c0f', 21) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_46ac5eb1c9', 22) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_b3a451b600', 23) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p2', 't_6d6941bf5f', 24) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r6p3', 'r6', 3, $mj$בית וקשרים$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_b78add04ac', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_9f195262d3', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_a35c1f4f17', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_a1e49c3bad', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_4f6f3eb9dd', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_757999bfee', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_08b7179c0f', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_28dcfa847e', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_6d6941bf5f', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_8229128602', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_46ac5eb1c9', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_b3a451b600', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_6c5ff14824', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_0d0d0f636c', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_c8fd439a8a', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_e62df589f9', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_6d8ad3dac6', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_36944a11eb', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_ead695b703', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_85a6fa4a01', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_6deca4cb5c', 21) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_ca281ca1ad', 22) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_3149473f1c', 23) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r6p3', 't_00ffb0476f', 24) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_price_ranges (id, label, min_ils, max_ils, task_count, sort_order) VALUES ('r7', $mj$5,000–7,500 ש״ח$mj$, 5000, 7500, 32, 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r7p1', 'r7', 1, $mj$צמיחה ויוזמה$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_a2ed1c9aa1', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_23379dee7c', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_a1e49c3bad', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_8d1d405dd9', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_3149473f1c', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_4f6f3eb9dd', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_9eb93eac2c', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_d698d1bb61', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_e9b8f2626d', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_46ac5eb1c9', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_c07c096103', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_d073688e9c', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_b3a451b600', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_47b9a10e48', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_8646c211a3', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_e98e0b31a9', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_36944a11eb', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_caa46b58fd', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_d0362bae5c', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_ead695b703', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_af79802265', 21) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_b3269810e4', 22) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_a157213497', 23) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_c0e0a9e8c3', 24) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_ee828534ba', 25) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_8f9f1777d7', 26) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_492ec611fe', 27) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_915ee91832', 28) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_6912dce8ed', 29) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_5d328d9a9f', 30) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_c182c55caa', 31) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p1', 't_739ca33861', 32) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r7p2', 'r7', 2, $mj$נתינה ומנהיגות$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_c182c55caa', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_3ebb1e4ab2', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_498ca4be6f', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_735fd7aee1', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_6912dce8ed', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_5d328d9a9f', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_739ca33861', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_a1e49c3bad', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_4f6f3eb9dd', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_9f195262d3', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_757999bfee', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_a35c1f4f17', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_b78add04ac', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_08b7179c0f', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_46ac5eb1c9', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_b3a451b600', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_6d6941bf5f', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_6c5ff14824', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_8229128602', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_28dcfa847e', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_0d0d0f636c', 21) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_36944a11eb', 22) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_ead695b703', 23) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_e62df589f9', 24) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_85a6fa4a01', 25) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_6d8ad3dac6', 26) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_c8fd439a8a', 27) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_6deca4cb5c', 28) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_c0e0a9e8c3', 29) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_492ec611fe', 30) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_3149473f1c', 31) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p2', 't_9eb93eac2c', 32) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r7p3', 'r7', 3, $mj$בית וקשרים$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_28dcfa847e', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_6d6941bf5f', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_8229128602', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_46ac5eb1c9', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_b3a451b600', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_6c5ff14824', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_0d0d0f636c', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_c8fd439a8a', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_e62df589f9', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_6d8ad3dac6', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_36944a11eb', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_ead695b703', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_85a6fa4a01', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_6deca4cb5c', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_ca281ca1ad', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_3149473f1c', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_00ffb0476f', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_c0e0a9e8c3', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_492ec611fe', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_9eb93eac2c', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_4cde197d65', 21) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_23379dee7c', 22) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_d073688e9c', 23) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_a2ed1c9aa1', 24) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_c182c55caa', 25) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_3ebb1e4ab2', 26) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_47b9a10e48', 27) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_bc857d3dbb', 28) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_e9b8f2626d', 29) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_d0362bae5c', 30) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_d698d1bb61', 31) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r7p3', 't_a1e49c3bad', 32) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_price_ranges (id, label, min_ils, max_ils, task_count, sort_order) VALUES ('r8', $mj$7,500–10,000 ש״ח$mj$, 7500, 10000, 36, 8) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r8p1', 'r8', 1, $mj$צמיחה ויוזמה$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_d698d1bb61', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_e9b8f2626d', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_46ac5eb1c9', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_c07c096103', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_d073688e9c', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_b3a451b600', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_47b9a10e48', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_8646c211a3', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_e98e0b31a9', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_36944a11eb', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_caa46b58fd', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_d0362bae5c', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_ead695b703', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_af79802265', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_b3269810e4', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_a157213497', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_c0e0a9e8c3', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_ee828534ba', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_8f9f1777d7', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_492ec611fe', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_915ee91832', 21) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_6912dce8ed', 22) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_5d328d9a9f', 23) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_c182c55caa', 24) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_739ca33861', 25) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_498ca4be6f', 26) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_3ebb1e4ab2', 27) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_735fd7aee1', 28) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_a35c1f4f17', 29) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_b78add04ac', 30) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_a1e49c3bad', 31) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_08b7179c0f', 32) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_9f195262d3', 33) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_4f6f3eb9dd', 34) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_757999bfee', 35) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p1', 't_8229128602', 36) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r8p2', 'r8', 2, $mj$נתינה ומנהיגות$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_a1e49c3bad', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_4f6f3eb9dd', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_9f195262d3', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_757999bfee', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_a35c1f4f17', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_b78add04ac', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_08b7179c0f', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_46ac5eb1c9', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_b3a451b600', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_6d6941bf5f', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_6c5ff14824', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_8229128602', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_28dcfa847e', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_0d0d0f636c', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_36944a11eb', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_ead695b703', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_e62df589f9', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_85a6fa4a01', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_6d8ad3dac6', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_c8fd439a8a', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_6deca4cb5c', 21) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_c0e0a9e8c3', 22) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_492ec611fe', 23) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_3149473f1c', 24) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_9eb93eac2c', 25) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_00ffb0476f', 26) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_ca281ca1ad', 27) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_4cde197d65', 28) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_c182c55caa', 29) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_3ebb1e4ab2', 30) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_d073688e9c', 31) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_47b9a10e48', 32) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_a2ed1c9aa1', 33) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_23379dee7c', 34) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_bc857d3dbb', 35) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p2', 't_d0362bae5c', 36) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r8p3', 'r8', 3, $mj$בית וקשרים$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_c8fd439a8a', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_e62df589f9', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_6d8ad3dac6', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_36944a11eb', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_ead695b703', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_85a6fa4a01', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_6deca4cb5c', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_ca281ca1ad', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_3149473f1c', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_00ffb0476f', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_c0e0a9e8c3', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_492ec611fe', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_9eb93eac2c', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_4cde197d65', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_23379dee7c', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_d073688e9c', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_a2ed1c9aa1', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_c182c55caa', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_3ebb1e4ab2', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_47b9a10e48', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_bc857d3dbb', 21) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_e9b8f2626d', 22) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_d0362bae5c', 23) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_d698d1bb61', 24) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_a1e49c3bad', 25) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_4f6f3eb9dd', 26) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_af79802265', 27) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_bf1806c81b', 28) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_e98e0b31a9', 29) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_8f9f1777d7', 30) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_8646c211a3', 31) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_46ac5eb1c9', 32) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_b3a451b600', 33) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_915ee91832', 34) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_8d1d405dd9', 35) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r8p3', 't_a157213497', 36) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_price_ranges (id, label, min_ils, max_ils, task_count, sort_order) VALUES ('r9', $mj$10,000 ש״ח ומעלה$mj$, 10000, NULL, 40, 9) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r9p1', 'r9', 1, $mj$צמיחה ויוזמה$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_8646c211a3', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_e98e0b31a9', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_36944a11eb', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_caa46b58fd', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_d0362bae5c', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_ead695b703', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_af79802265', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_b3269810e4', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_a157213497', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_c0e0a9e8c3', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_ee828534ba', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_8f9f1777d7', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_492ec611fe', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_915ee91832', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_6912dce8ed', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_5d328d9a9f', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_c182c55caa', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_739ca33861', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_498ca4be6f', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_3ebb1e4ab2', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_735fd7aee1', 21) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_a35c1f4f17', 22) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_b78add04ac', 23) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_a1e49c3bad', 24) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_08b7179c0f', 25) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_9f195262d3', 26) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_4f6f3eb9dd', 27) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_757999bfee', 28) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_8229128602', 29) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_28dcfa847e', 30) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_46ac5eb1c9', 31) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_0d0d0f636c', 32) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_6d6941bf5f', 33) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_b3a451b600', 34) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_6c5ff14824', 35) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_6d8ad3dac6', 36) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_c8fd439a8a', 37) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_6deca4cb5c', 38) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_e62df589f9', 39) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p1', 't_85a6fa4a01', 40) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r9p2', 'r9', 2, $mj$נתינה ומנהיגות$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_46ac5eb1c9', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_b3a451b600', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_6d6941bf5f', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_6c5ff14824', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_8229128602', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_28dcfa847e', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_0d0d0f636c', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_36944a11eb', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_ead695b703', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_e62df589f9', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_85a6fa4a01', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_6d8ad3dac6', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_c8fd439a8a', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_6deca4cb5c', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_c0e0a9e8c3', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_492ec611fe', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_3149473f1c', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_9eb93eac2c', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_00ffb0476f', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_ca281ca1ad', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_4cde197d65', 21) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_c182c55caa', 22) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_3ebb1e4ab2', 23) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_d073688e9c', 24) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_47b9a10e48', 25) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_a2ed1c9aa1', 26) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_23379dee7c', 27) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_bc857d3dbb', 28) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_a1e49c3bad', 29) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_4f6f3eb9dd', 30) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_d0362bae5c', 31) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_af79802265', 32) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_d698d1bb61', 33) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_e9b8f2626d', 34) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_bf1806c81b', 35) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_8f9f1777d7', 36) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_915ee91832', 37) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_8646c211a3', 38) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_e98e0b31a9', 39) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p2', 't_8d1d405dd9', 40) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_paths (id, range_id, path_index, name) VALUES ('r9p3', 'r9', 3, $mj$בית וקשרים$mj$) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_ca281ca1ad', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_3149473f1c', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_00ffb0476f', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_c0e0a9e8c3', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_492ec611fe', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_9eb93eac2c', 6) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_4cde197d65', 7) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_23379dee7c', 8) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_d073688e9c', 9) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_a2ed1c9aa1', 10) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_c182c55caa', 11) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_3ebb1e4ab2', 12) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_47b9a10e48', 13) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_bc857d3dbb', 14) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_e9b8f2626d', 15) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_d0362bae5c', 16) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_d698d1bb61', 17) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_a1e49c3bad', 18) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_4f6f3eb9dd', 19) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_af79802265', 20) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_bf1806c81b', 21) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_e98e0b31a9', 22) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_8f9f1777d7', 23) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_8646c211a3', 24) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_46ac5eb1c9', 25) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_b3a451b600', 26) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_915ee91832', 27) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_8d1d405dd9', 28) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_a157213497', 29) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_498ca4be6f', 30) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_b3269810e4', 31) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_36944a11eb', 32) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_ead695b703', 33) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_735fd7aee1', 34) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_c07c096103', 35) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_5d328d9a9f', 36) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_9f195262d3', 37) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_6912dce8ed', 38) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_757999bfee', 39) ON CONFLICT DO NOTHING;
INSERT INTO public.reward_path_tasks (path_id, task_id, sort_order) VALUES ('r9p3', 't_caa46b58fd', 40) ON CONFLICT DO NOTHING;
INSERT INTO public.content_categories (id, name, sort_order) VALUES ('c1', $mj$למידה, התפתחות ומיומנויות אישיות$mj$, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.content_categories (id, name, sort_order) VALUES ('c2', $mj$גיבוש משפחתי ואחריות בבית$mj$, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.content_categories (id, name, sort_order) VALUES ('c3', $mj$קהילה, התנדבות ונתינה$mj$, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.content_categories (id, name, sort_order) VALUES ('c4', $mj$יוזמה, עסקים ומסחר$mj$, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.content_categories (id, name, sort_order) VALUES ('c5', $mj$מנהיגות, הנחיה וחונכות$mj$, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.content_categories (id, name, sort_order) VALUES ('c6', $mj$קשר בין־דורי וכבוד לגיל השלישי$mj$, 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.content_categories (id, name, sort_order) VALUES ('c7', $mj$אחריות סביבתית ובעלי חיים$mj$, 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_b3269810e4', $mj$פותחים את הראש!$mj$, $mj$למידה, התפתחות ומיומנויות אישיות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_a157213497', $mj$אלופי התקציב!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_c182c55caa', $mj$גיבורים למען הקהילה!$mj$, $mj$קהילה, התנדבות ונתינה$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_08b7179c0f', $mj$עושים מהלימון לימונדה!$mj$, $mj$יוזמה, עסקים ומסחר$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_c0e0a9e8c3', $mj$מושיטים יד!$mj$, $mj$קהילה, התנדבות ונתינה$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_492ec611fe', $mj$מנחי סדנאות!$mj$, $mj$מנהיגות, הנחיה וחונכות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_6d6941bf5f', $mj$מתכון מהבית של סבתא!$mj$, $mj$קשר בין־דורי וכבוד לגיל השלישי$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_6d8ad3dac6', $mj$אלופי ההרגל הטוב!$mj$, $mj$למידה, התפתחות ומיומנויות אישיות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_23379dee7c', $mj$מנהלי הלו״ז של סופ״ש!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_3149473f1c', $mj$אל תשליכני לעת זקנה!$mj$, $mj$קשר בין־דורי וכבוד לגיל השלישי$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_a2ed1c9aa1', $mj$תולעי ספרים!$mj$, $mj$למידה, התפתחות ומיומנויות אישיות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_a1e49c3bad', $mj$מעבירים את הטוב הלאה!$mj$, $mj$קהילה, התנדבות ונתינה$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_6912dce8ed', $mj$הנדימן צעיר!$mj$, $mj$למידה, התפתחות ומיומנויות אישיות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_5d328d9a9f', $mj$מנהלי הבית התורנים!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_0d0d0f636c', $mj$ביזנס־טיים!$mj$, $mj$יוזמה, עסקים ומסחר$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_8f9f1777d7', $mj$תמיכה טכנית VIP!$mj$, $mj$קשר בין־דורי וכבוד לגיל השלישי$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_4f6f3eb9dd', $mj$מדריכים צעירים!$mj$, $mj$מנהיגות, הנחיה וחונכות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_3ebb1e4ab2', $mj$יושבי ראש הישיבה המשפחתית!$mj$, $mj$מנהיגות, הנחיה וחונכות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_e62df589f9', $mj$חברים למרות ההפרש!$mj$, $mj$קשר בין־דורי וכבוד לגיל השלישי$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_85a6fa4a01', $mj$הולכים על ארבע!$mj$, $mj$אחריות סביבתית ובעלי חיים$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_00ffb0476f', $mj$משקיעים בעתיד!$mj$, $mj$למידה, התפתחות ומיומנויות אישיות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_bf1806c81b', $mj$קונדיטורים בהזמנה אישית!$mj$, $mj$יוזמה, עסקים ומסחר$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_e9b8f2626d', $mj$סטייליסטים אישיים!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_d073688e9c', $mj$שורשים וסיפורים!$mj$, $mj$קשר בין־דורי וכבוד לגיל השלישי$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_d698d1bb61', $mj$סקיל חדש!$mj$, $mj$למידה, התפתחות ומיומנויות אישיות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_46ac5eb1c9', $mj$שגרירי חסד שבועיים!$mj$, $mj$קהילה, התנדבות ונתינה$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_b3a451b600', $mj$אח גדול, מורה גדול!$mj$, $mj$מנהיגות, הנחיה וחונכות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_47b9a10e48', $mj$שומרי הפינה הירוקה!$mj$, $mj$אחריות סביבתית ובעלי חיים$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_a35c1f4f17', $mj$יומן ההצלחות!$mj$, $mj$למידה, התפתחות ומיומנויות אישיות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_b78add04ac', $mj$אלבום הזיכרונות המשפחתי!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_6deca4cb5c', $mj$עושים סדר, עושים כסף!$mj$, $mj$יוזמה, עסקים ומסחר$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_498ca4be6f', $mj$דיגיטל לכל גיל!$mj$, $mj$קשר בין־דורי וכבוד לגיל השלישי$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_735fd7aee1', $mj$ממחזרים ומרוויחים!$mj$, $mj$אחריות סביבתית ובעלי חיים$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_8229128602', $mj$מומחים לנושא אחד!$mj$, $mj$למידה, התפתחות ומיומנויות אישיות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_9eb93eac2c', $mj$דוג־סיטר מקצועי!$mj$, $mj$אחריות סביבתית ובעלי חיים$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_8d1d405dd9', $mj$מעצבים ומוכרים!$mj$, $mj$יוזמה, עסקים ומסחר$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_e98e0b31a9', $mj$כתבים משפחתיים!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_d0362bae5c', $mj$שכנות טובה משתלמת!$mj$, $mj$קשר בין־דורי וכבוד לגיל השלישי$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_8646c211a3', $mj$אלופים בתנועה!$mj$, $mj$למידה, התפתחות ומיומנויות אישיות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_36944a11eb', $mj$מגייסי הטוב!$mj$, $mj$קהילה, התנדבות ונתינה$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_ead695b703', $mj$מפיקי אירועים!$mj$, $mj$מנהיגות, הנחיה וחונכות$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_af79802265', $mj$מפרידי האשפה המקצוענים!$mj$, $mj$אחריות סביבתית ובעלי חיים$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_caa46b58fd', $mj$מנכ״לים בהקמה!$mj$, $mj$יוזמה, עסקים ומסחר$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_28dcfa847e', $mj$כלכלני הבית הצעירים!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_4cde197d65', $mj$יוצרים ומוכרים!$mj$, $mj$יוזמה, עסקים ומסחר$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_9f195262d3', $mj$מפיקי פודקאסט משפחתי!$mj$, $mj$קשר בין־דורי וכבוד לגיל השלישי$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_757999bfee', $mj$אמנות ממוחזרת!$mj$, $mj$אחריות סביבתית ובעלי חיים$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_c8fd439a8a', $mj$זמן משפחה בהפקתכם!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_bc857d3dbb', $mj$מבריקים בדרכים!$mj$, $mj$יוזמה, עסקים ומסחר$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_6c5ff14824', $mj$משתלה ביתית!$mj$, $mj$אחריות סביבתית ובעלי חיים$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_c07c096103', $mj$בייביסיטר של אחר הצהריים!$mj$, $mj$יוזמה, עסקים ומסחר$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_915ee91832', $mj$ידידי בעלי הכנף!$mj$, $mj$אחריות סביבתית ובעלי חיים$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_ee828534ba', $mj$לקוח מרוצה חוזר!$mj$, $mj$יוזמה, עסקים ומסחר$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_739ca33861', $mj$יזמי הצילום!$mj$, $mj$יוזמה, עסקים ומסחר$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_ca281ca1ad', $mj$מאסטר שף צעיר!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'action') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_33bd662546', $mj$להתראות אשפה!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'home') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_e1b409b28d', $mj$טיפול בחיית המחמד זה נחמד!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'home') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_c320315275', $mj$הכביסה במנוסה!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'home') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_db8fec55d3', $mj$הכיור מנצנץ!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'home') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_7820d5f3c2', $mj$החדר טיפ-טופ!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'home') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_24193a1eda', $mj$השומר הצעיר!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'home') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_9210e33ec5', $mj$תקתוק של ארון הבגדים!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'home') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_c4b3d5463e', $mj$כן שף!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'home') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.reward_tasks (id, title, category, kind) VALUES ('t_465b5cfacb', $mj$הבית דנדש!$mj$, $mj$גיבוש משפחתי ואחריות בבית$mj$, 'home') ON CONFLICT (id) DO NOTHING;
